-- ============================================================
-- post_categories (10 records)
-- ============================================================
INSERT INTO post_categories (name, image_url, status, created_at, created_by) VALUES
('Technology',      'https://picsum.photos/seed/tech/400/300',        'ACT', NOW(), 'system'),
('Travel',          'https://picsum.photos/seed/travel/400/300',       'ACT', NOW(), 'system'),
('Food & Cooking',  'https://picsum.photos/seed/food/400/300',         'ACT', NOW(), 'system'),
('Health & Fitness','https://picsum.photos/seed/health/400/300',       'ACT', NOW(), 'system'),
('Business',        'https://picsum.photos/seed/business/400/300',     'ACT', NOW(), 'system'),
('Entertainment',   'https://picsum.photos/seed/entertain/400/300',    'ACT', NOW(), 'system'),
('Sports',          'https://picsum.photos/seed/sports/400/300',       'ACT', NOW(), 'system'),
('Science',         'https://picsum.photos/seed/science/400/300',      'ACT', NOW(), 'system'),
('Education',       'https://picsum.photos/seed/education/400/300',    'ACT', NOW(), 'system'),
('Lifestyle',       'https://picsum.photos/seed/lifestyle/400/300',    'ACT', NOW(), 'system');

-- ============================================================
-- posts (100 records — 10 per category)
-- ============================================================

-- Category 1: Technology
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('The Rise of Artificial Intelligence',        'AI is transforming every industry.',       'Artificial intelligence is no longer a futuristic concept — it is embedded in search engines, medical diagnostics, autonomous vehicles, and everyday apps. From machine learning models that predict consumer behaviour to neural networks that generate art, AI is reshaping how humans interact with technology at every level.',       120, 45, 3, 'ACT', 'https://picsum.photos/seed/ai/800/600',       1, NULL, NOW() - INTERVAL '90 days', 'system'),
('Understanding Cloud Computing',              'Everything you need to know about the cloud.','Cloud computing delivers on-demand computing services over the internet, including storage, databases, networking, and software. Providers like AWS, Azure, and Google Cloud offer flexible pricing models that allow startups and enterprises alike to scale infrastructure without heavy upfront investment.',                    98,  30, 2, 'ACT', 'https://picsum.photos/seed/cloud/800/600',    1, NULL, NOW() - INTERVAL '87 days', 'system'),
('Blockchain Beyond Cryptocurrency',           'Blockchain has uses far beyond Bitcoin.',  'While most people associate blockchain with Bitcoin, the technology underpins a wide range of applications: supply-chain transparency, digital identity, healthcare records, and smart contracts. Decentralised ledgers remove the need for a central authority, reducing fraud and increasing auditability.',                     75,  22, 5, 'ACT', 'https://picsum.photos/seed/blockchain/800/600',1, NULL, NOW() - INTERVAL '84 days', 'system'),
('Cybersecurity in the Modern Era',            'Protecting your digital life.',            'Cyberattacks cost businesses trillions of dollars annually. Phishing, ransomware, and zero-day exploits continue to evolve faster than many organisations can respond. Implementing zero-trust architecture, multi-factor authentication, and regular penetration testing are baseline defences for 2024.',                       60,  18, 1, 'ACT', 'https://picsum.photos/seed/cyber/800/600',    1, NULL, NOW() - INTERVAL '81 days', 'system'),
('The Future of 5G Networks',                 'How 5G will change connectivity.',         '5G promises speeds up to 100 times faster than 4G with significantly lower latency. Beyond faster phones, 5G enables massive IoT deployments, real-time remote surgery, and smart-city infrastructure. Widespread rollout is expected to complete in most urban markets by 2026.',                                              88,  35, 4, 'ACT', 'https://picsum.photos/seed/5g/800/600',       1, NULL, NOW() - INTERVAL '78 days', 'system'),
('Quantum Computing Explained',                'A beginner-friendly guide to qubits.',    'Quantum computers harness quantum mechanical phenomena such as superposition and entanglement to perform calculations that would take classical computers millions of years. While still largely experimental, companies like IBM and Google have demonstrated quantum advantage on specific tasks.',                             55,  20, 2, 'ACT', 'https://picsum.photos/seed/quantum/800/600',  1, NULL, NOW() - INTERVAL '75 days', 'system'),
('Open Source Software Revolution',           'How open source changed the world.',       'From the Linux kernel to the Android operating system, open-source software powers the internet. Collaborative development models reduce duplication, accelerate innovation, and allow peer review that improves security. Corporations now invest heavily in open-source projects as a strategic advantage.',                   70,  28, 1, 'ACT', 'https://picsum.photos/seed/opensource/800/600',1, NULL, NOW() - INTERVAL '72 days', 'system'),
('Machine Learning for Beginners',            'Start your ML journey here.',              'Machine learning is a subset of AI that enables systems to learn from data without being explicitly programmed. Supervised learning, unsupervised learning, and reinforcement learning are the three major paradigms. Python libraries like scikit-learn, TensorFlow, and PyTorch make experimentation accessible to beginners.',105, 40, 3, 'ACT', 'https://picsum.photos/seed/ml/800/600',       1, NULL, NOW() - INTERVAL '69 days', 'system'),
('DevOps Best Practices',                     'Ship faster with fewer bugs.',             'DevOps bridges the gap between development and operations teams, promoting continuous integration and continuous delivery (CI/CD). Infrastructure as code, automated testing pipelines, container orchestration with Kubernetes, and observability tools like Prometheus and Grafana are core pillars of a mature DevOps practice.',  90, 32, 2, 'ACT', 'https://picsum.photos/seed/devops/800/600',   1, NULL, NOW() - INTERVAL '66 days', 'system'),
('React vs Vue vs Angular in 2024',           'Choosing the right frontend framework.',   'Each major frontend framework has its strengths. React offers a vast ecosystem and flexibility. Vue is praised for its gentle learning curve and excellent documentation. Angular provides an opinionated, batteries-included structure ideal for large enterprise teams. The best choice depends on team size, project scope, and existing expertise.', 135, 50, 6, 'ACT', 'https://picsum.photos/seed/frontend/800/600', 1, NULL, NOW() - INTERVAL '63 days', 'system');

-- Category 2: Travel
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('Top 10 Hidden Gems in Southeast Asia',      'Escape the tourist crowds.',               'Southeast Asia is famed for its beaches and temples, but venture off the beaten path and you will discover terraced rice fields in northern Vietnam, the ancient ruins of Mrauk-U in Myanmar, pristine islands in the Philippines, and the colonial charm of Kampot, Cambodia.',                                               200, 80, 5, 'ACT', 'https://picsum.photos/seed/sea/800/600',      2, NULL, NOW() - INTERVAL '88 days', 'system'),
('Backpacking Europe on a Budget',            'Explore Europe without breaking the bank.','With budget airlines, hostel networks, and rail passes, Europe is more affordable than many travellers think. Prioritise Eastern European cities like Kraków, Bratislava, and Sofia where your money stretches further. Cook your own meals, travel overnight to save on accommodation, and book sights in advance.',          175, 65, 4, 'ACT', 'https://picsum.photos/seed/europe/800/600',   2, NULL, NOW() - INTERVAL '85 days', 'system'),
('Solo Travel Safety Tips',                   'Stay safe while exploring alone.',         'Solo travel is one of life''s most rewarding experiences, but preparation is essential. Share your itinerary with someone you trust, keep digital copies of documents, purchase comprehensive travel insurance, and research local scams before arriving. Trust your instincts — if something feels wrong, leave.',               145, 55, 3, 'ACT', 'https://picsum.photos/seed/solo/800/600',     2, NULL, NOW() - INTERVAL '82 days', 'system'),
('The Best Street Food Cities in the World',  'Eat your way around the globe.',          'Bangkok, Mexico City, Marrakech, Hanoi, and Istanbul consistently rank among the world''s best street food destinations. Street food is not only affordable but often the most authentic representation of local culinary culture, prepared by vendors who have perfected a single dish over decades.',                         190, 72, 6, 'ACT', 'https://picsum.photos/seed/streetfood/800/600',2, NULL, NOW() - INTERVAL '79 days', 'system'),
('How to Travel with Kids',                   'Family travel made easy.',                 'Travelling with children requires more planning but yields unforgettable family memories. Choose destinations with good medical facilities and child-friendly activities. Pack light, travel slow, and build buffer time into every day. Involving kids in the planning builds excitement and reduces friction on the road.',       130, 48, 2, 'ACT', 'https://picsum.photos/seed/family/800/600',   2, NULL, NOW() - INTERVAL '76 days', 'system'),
('A Week in Japan: Itinerary Guide',          'Tokyo, Kyoto, Osaka and beyond.',         'Japan rewards careful planning. Spend three days in Tokyo exploring Shinjuku, Akihabara, and Shibuya. Take the Shinkansen to Kyoto for temples and geisha culture. Finish in Osaka for world-class street food. A 14-day JR Pass covers unlimited Shinkansen travel and pays for itself quickly.',                          210, 85, 4, 'ACT', 'https://picsum.photos/seed/japan/800/600',    2, NULL, NOW() - INTERVAL '73 days', 'system'),
('Sustainable Travel: How to Reduce Impact',  'Travel more responsibly.',                 'Sustainable travel means minimising your carbon footprint, respecting local cultures, and supporting community-based tourism. Choose direct flights when possible, stay in locally owned guesthouses, eat at family restaurants, hire local guides, and avoid single-use plastics throughout your journey.',                    115, 42, 3, 'ACT', 'https://picsum.photos/seed/sustainable/800/600',2, NULL, NOW() - INTERVAL '70 days', 'system'),
('Digital Nomad Guide: Best Cities to Work',  'Work remotely from anywhere.',            'Chiang Mai, Medellín, Lisbon, Tbilisi, and Bali top the 2024 digital nomad rankings for affordable cost of living, fast internet, vibrant coworking scenes, and welcoming visa policies. Many countries now offer dedicated digital nomad visas lasting one to two years.',                                                 180, 68, 5, 'ACT', 'https://picsum.photos/seed/nomad/800/600',    2, NULL, NOW() - INTERVAL '67 days', 'system'),
('Road Trip: Driving Route 66',               'The ultimate American road trip.',         'Route 66 stretches 3,940 km from Chicago to Santa Monica. Along the way you will encounter classic diners, neon-lit motels, the Cadillac Ranch art installation, the Petrified Forest National Park, and the sweeping vistas of the Mojave Desert. Allow at least two weeks to do it justice.',                            165, 60, 4, 'ACT', 'https://picsum.photos/seed/route66/800/600',  2, NULL, NOW() - INTERVAL '64 days', 'system'),
('Travel Photography Tips for Beginners',     'Capture better travel memories.',         'Great travel photography is about light, composition, and patience. The golden hour — shortly after sunrise and before sunset — provides the most flattering natural light. Use the rule of thirds, get low to the ground for interesting angles, and always ask permission before photographing people.',                      155, 58, 3, 'ACT', 'https://picsum.photos/seed/photo/800/600',    2, NULL, NOW() - INTERVAL '61 days', 'system');

-- Category 3: Food & Cooking
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('Mastering the Perfect Pasta',               'Italian cooking secrets revealed.',        'Perfect pasta starts with the right flour-to-egg ratio and kneading technique. Tipo 00 flour produces silkier dough, while semolina adds bite. Rest the dough for 30 minutes before rolling. Salt your water generously — it should taste like the sea — and pull pasta one minute before the stated cooking time.',        145, 55, 2, 'ACT', 'https://picsum.photos/seed/pasta/800/600',    3, NULL, NOW() - INTERVAL '86 days', 'system'),
('The Science of Bread Baking',               'Why your bread rises — and why it doesn''t.','Bread making is applied chemistry. Yeast consumes sugars and produces CO₂ that makes dough rise. Gluten networks trap those gas bubbles, creating airy structure. Over-proofing collapses the structure; under-proofing produces dense loaves. Water temperature, humidity, and flour protein content all affect the result.', 130, 48, 3, 'ACT', 'https://picsum.photos/seed/bread/800/600',    3, NULL, NOW() - INTERVAL '83 days', 'system'),
('10 Essential Knife Skills',                 'Cut like a professional chef.',            'A sharp knife is safer than a dull one. Master the pinch grip, the claw technique for guiding vegetables, and the rocking motion for herbs. Learn the julienne, brunoise, chiffonade, and rough chop. A well-maintained 20 cm chef''s knife will handle 90 percent of kitchen tasks.',                                       110, 40, 1, 'ACT', 'https://picsum.photos/seed/knife/800/600',    3, NULL, NOW() - INTERVAL '80 days', 'system'),
('Fermentation at Home: A Beginner''s Guide',  'Make kimchi, kombucha and more.',        'Fermentation is one of humanity''s oldest food preservation techniques. Salt, time, and beneficial bacteria transform vegetables, dairy, and grains into complex, probiotic-rich foods. Start with sauerkraut — just cabbage and salt — before advancing to kimchi, miso, sourdough starter, or jun tea.',                  95,  35, 2, 'ACT', 'https://picsum.photos/seed/ferment/800/600',  3, NULL, NOW() - INTERVAL '77 days', 'system'),
('Plant-Based Cooking for Meat Lovers',       'Delicious vegan meals you will actually enjoy.','Plant-based cooking has evolved far beyond salads. Techniques like charring, caramelising, marinating, and smoking create deep umami flavours in vegetables, legumes, and tofu. Jackfruit pulled pork, lentil bolognese, and smoked beetroot tartare can satisfy even committed carnivores.',                              125, 46, 4, 'ACT', 'https://picsum.photos/seed/vegan/800/600',    3, NULL, NOW() - INTERVAL '74 days', 'system'),
('Meal Prep for the Busy Professional',       'Cook once, eat all week.',                 'Effective meal prep reduces decision fatigue, saves money, and supports consistent healthy eating. Batch-cook proteins on Sunday, prepare versatile grains like quinoa or brown rice, and roast a sheet pan of vegetables. Store components separately for maximum flexibility throughout the week.',                           100, 38, 2, 'ACT', 'https://picsum.photos/seed/mealprep/800/600', 3, NULL, NOW() - INTERVAL '71 days', 'system'),
('Understanding Umami: The Fifth Taste',      'The secret behind the most satisfying dishes.','Umami, discovered by Japanese chemist Kikunae Ikeda in 1908, is triggered by glutamate compounds. Foods naturally rich in umami include aged parmesan, anchovies, soy sauce, mushrooms, tomatoes, and miso. Combining two umami-rich ingredients creates a synergistic effect that amplifies the savoury sensation.',     88,  32, 1, 'ACT', 'https://picsum.photos/seed/umami/800/600',    3, NULL, NOW() - INTERVAL '68 days', 'system'),
('Cocktail Mixing Basics',                    'Make bar-quality drinks at home.',        'Great cocktails balance sweet, sour, strong, and bitter elements. Invest in a jigger for accurate measures, a Boston shaker, a Hawthorne strainer, and a bar spoon. Learn five classic templates — the Old Fashioned, Daiquiri, Margarita, Negroni, and Whisky Sour — and you can riff on hundreds of variations.',          115, 42, 5, 'ACT', 'https://picsum.photos/seed/cocktail/800/600', 3, NULL, NOW() - INTERVAL '65 days', 'system'),
('The Art of Sourdough',                      'Your complete sourdough starter guide.',   'A sourdough starter is a living culture of wild yeast and lactic acid bacteria maintained with regular feedings of flour and water. Once active, it leavens bread without commercial yeast and imparts a complex tang. Maintain your starter in the fridge between bakes and feed it 4–12 hours before use.',                 140, 52, 3, 'ACT', 'https://picsum.photos/seed/sourdough/800/600',3, NULL, NOW() - INTERVAL '62 days', 'system'),
('Coffee Brewing Methods Compared',           'From espresso to pour-over.',             'Each brewing method extracts coffee differently. Espresso uses high pressure for a concentrated shot with crema. Pour-over allows full control over water temperature and flow rate for a clean, nuanced cup. French press produces a full-bodied brew. Cold brew steeps coarse grounds in cold water for 12–24 hours for low-acidity coffee.',  160, 60, 4, 'ACT', 'https://picsum.photos/seed/coffee/800/600',   3, NULL, NOW() - INTERVAL '59 days', 'system');

-- Category 4: Health & Fitness
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('Strength Training for Beginners',           'Build muscle and confidence from day one.','Starting a strength training programme can feel overwhelming, but the fundamentals are simple: compound lifts like squats, deadlifts, bench presses, and rows build total-body strength efficiently. Begin with bodyweight movements to learn form, progress to a barbell, and prioritise consistent sleep and adequate protein intake.',  180, 70, 4, 'ACT', 'https://picsum.photos/seed/strength/800/600', 4, NULL, NOW() - INTERVAL '89 days', 'system'),
('The Benefits of Daily Walking',             'Why 10,000 steps matters.',               'Walking is one of the most underrated forms of exercise. A daily 30-minute walk reduces cardiovascular risk, improves mood, supports weight management, and requires no equipment or gym membership. Studies show brisk walking after meals specifically reduces blood glucose spikes in people with type 2 diabetes.',             155, 58, 2, 'ACT', 'https://picsum.photos/seed/walking/800/600',  4, NULL, NOW() - INTERVAL '86 days', 'system'),
('Sleep Optimisation Guide',                  'Sleep better, perform better.',            'Adults need 7–9 hours of quality sleep per night. Optimise your sleep environment by keeping the room cool (18°C), dark, and quiet. Avoid screens for 60 minutes before bed, limit caffeine after noon, and maintain a consistent sleep schedule — even on weekends. Good sleep improves memory consolidation, hormone regulation, and immune function.', 165, 62, 3, 'ACT', 'https://picsum.photos/seed/sleep/800/600',    4, NULL, NOW() - INTERVAL '83 days', 'system'),
('Nutrition Basics: Macros Explained',        'Proteins, carbs, and fats demystified.',  'Macronutrients are the three energy-providing nutrients: protein (4 kcal/g), carbohydrates (4 kcal/g), and fat (9 kcal/g). Protein supports muscle synthesis and satiety. Carbohydrates fuel the brain and muscles. Dietary fats regulate hormones and aid vitamin absorption. The optimal ratio depends on your goals and activity level.',  140, 52, 3, 'ACT', 'https://picsum.photos/seed/nutrition/800/600', 4, NULL, NOW() - INTERVAL '80 days', 'system'),
('Mental Health and Exercise Connection',     'How movement transforms your mind.',      'Exercise triggers the release of endorphins, dopamine, and serotonin — neurotransmitters that regulate mood, motivation, and reward. Regular physical activity has been shown to reduce symptoms of depression and anxiety with effectiveness comparable to antidepressant medication in mild-to-moderate cases.',                   195, 75, 5, 'ACT', 'https://picsum.photos/seed/mental/800/600',   4, NULL, NOW() - INTERVAL '77 days', 'system'),
('Intermittent Fasting: What the Science Says','Is IF right for you?',                   'Intermittent fasting (IF) involves cycling between periods of eating and fasting. The 16:8 method — fasting for 16 hours and eating within an 8-hour window — is the most popular. Research suggests IF can aid weight loss, improve insulin sensitivity, and reduce inflammation, but results vary significantly between individuals.',  150, 56, 6, 'ACT', 'https://picsum.photos/seed/fasting/800/600',  4, NULL, NOW() - INTERVAL '74 days', 'system'),
('Yoga for Stress Relief',                    'Find calm through movement and breath.',   'Yoga combines physical postures, breathwork, and meditation to reduce the physiological stress response. Even a 20-minute practice of slow, restorative poses like Child''s Pose, Legs-up-the-Wall, and Supine Twist activates the parasympathetic nervous system, lowering cortisol and heart rate.',                              120, 45, 2, 'ACT', 'https://picsum.photos/seed/yoga/800/600',     4, NULL, NOW() - INTERVAL '71 days', 'system'),
('Cold Showers: Benefits and How to Start',   'The case for turning the dial to cold.',  'Cold exposure activates brown adipose tissue, boosts alertness via noradrenaline release, and may speed muscle recovery. Start by finishing your regular shower with 30 seconds of cold water and gradually extend the duration. The Wim Hof breathing method is often practised alongside cold therapy for amplified effect.',     105, 38, 4, 'ACT', 'https://picsum.photos/seed/cold/800/600',     4, NULL, NOW() - INTERVAL '68 days', 'system'),
('Building a Home Gym on a Budget',           'Effective training without a membership.','A pull-up bar, resistance bands, a pair of adjustable dumbbells, and a jump rope cover the majority of fitness goals for under $200. Add a kettlebell and a gymnastic ring set and you have equipment that rivals a commercial gym for functional strength and conditioning.',                                                       135, 50, 3, 'ACT', 'https://picsum.photos/seed/homegym/800/600',  4, NULL, NOW() - INTERVAL '65 days', 'system'),
('Running Your First 5K',                     'A beginner training plan.',               'The Couch to 5K (C25K) programme takes complete beginners from zero running fitness to completing a 5-kilometre run in nine weeks. Alternating walking and running intervals three times per week builds aerobic capacity gradually without injury. Invest in proper running shoes fitted at a specialist store before you start.',   145, 54, 2, 'ACT', 'https://picsum.photos/seed/5k/800/600',       4, NULL, NOW() - INTERVAL '62 days', 'system');

-- Category 5: Business
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('How to Write a Business Plan',              'Structure your vision for success.',      'A strong business plan defines your value proposition, target market, competitive landscape, operational structure, and financial projections. Investors and lenders use it to assess risk. Keep it concise — a focused 20-page document with clear data is more persuasive than a sprawling 80-page report.',                     160, 60, 4, 'ACT', 'https://picsum.photos/seed/bizplan/800/600',  5, NULL, NOW() - INTERVAL '87 days', 'system'),
('Digital Marketing Fundamentals',            'Grow your audience online.',              'Digital marketing encompasses SEO, content marketing, social media, email campaigns, pay-per-click advertising, and analytics. A data-driven approach — setting clear KPIs, A/B testing copy, and continuously analysing conversion funnels — consistently outperforms gut-feel decisions.',                                       145, 54, 3, 'ACT', 'https://picsum.photos/seed/marketing/800/600', 5, NULL, NOW() - INTERVAL '84 days', 'system'),
('Productivity Systems That Actually Work',   'Get more done in less time.',             'The most effective productivity systems share common principles: capture every commitment outside your head, process tasks regularly, and focus single-mindedly on one priority at a time. GTD (Getting Things Done), time-blocking, and the Pomodoro technique are proven frameworks worth experimenting with.',                   175, 66, 5, 'ACT', 'https://picsum.photos/seed/productivity/800/600',5, NULL, NOW() - INTERVAL '81 days', 'system'),
('The Art of Negotiation',                    'How to get more of what you want.',       'Effective negotiators prepare thoroughly, listen more than they speak, and aim for outcomes that create value for both parties. Anchoring — making the first offer — strongly influences final outcomes. BATNA (Best Alternative to a Negotiated Agreement) is the single most important concept to understand before any negotiation.',130, 48, 2, 'ACT', 'https://picsum.photos/seed/negotiation/800/600',5, NULL, NOW() - INTERVAL '78 days', 'system'),
('Building a Personal Brand',                 'Stand out in a crowded market.',          'A personal brand communicates your unique value, expertise, and personality consistently across platforms. Define your niche, create and share original content regularly, engage authentically with your audience, and be patient — meaningful personal brands are built over years, not weeks.',                                    115, 42, 3, 'ACT', 'https://picsum.photos/seed/brand/800/600',    5, NULL, NOW() - INTERVAL '75 days', 'system'),
('Remote Team Management',                    'Lead distributed teams effectively.',     'Managing remote teams requires deliberate communication rhythms, clear documentation, and trust-based leadership. Establish asynchronous communication norms, use project management tools like Linear or Notion, over-communicate context rather than just instructions, and schedule regular 1:1 video calls to maintain connection.',  140, 52, 4, 'ACT', 'https://picsum.photos/seed/remote/800/600',   5, NULL, NOW() - INTERVAL '72 days', 'system'),
('Understanding Financial Statements',        'Read a balance sheet with confidence.',   'Three core financial statements tell the story of a business: the income statement (profitability), the balance sheet (assets, liabilities, and equity at a point in time), and the cash flow statement (how cash moves in and out). Ratio analysis — liquidity, solvency, and profitability ratios — reveals the health behind the numbers.', 120, 45, 2, 'ACT', 'https://picsum.photos/seed/finance/800/600',   5, NULL, NOW() - INTERVAL '69 days', 'system'),
('Startup Funding Stages Explained',          'From pre-seed to IPO.',                   'Startups progress through distinct funding stages. Pre-seed capital (friends, family, angels) proves concept. Seed rounds ($500K–$2M) fund product-market fit. Series A ($2M–$15M) scales a proven model. Series B and C fund aggressive growth. Venture debt, strategic partnerships, and IPOs provide later-stage options.',     135, 50, 3, 'ACT', 'https://picsum.photos/seed/startup/800/600',  5, NULL, NOW() - INTERVAL '66 days', 'system'),
('Customer Experience Design',                'Build products people love.',             'Customer experience (CX) encompasses every interaction a person has with your brand — from first awareness through purchase to support. Journey mapping, user research, net promoter score tracking, and rapid iteration on pain points are the disciplines that separate CX leaders from laggards.',                                 100, 38, 2, 'ACT', 'https://picsum.photos/seed/cx/800/600',       5, NULL, NOW() - INTERVAL '63 days', 'system'),
('Supply Chain Resilience',                   'Lessons from global disruptions.',        'The COVID-19 pandemic exposed the fragility of just-in-time global supply chains. Companies are now diversifying suppliers, nearshoring production, building strategic inventory buffers, and investing in real-time supply chain visibility platforms. Resilience has replaced pure cost-optimisation as the primary objective.',   90,  33, 2, 'ACT', 'https://picsum.photos/seed/supply/800/600',   5, NULL, NOW() - INTERVAL '60 days', 'system');

-- Category 6: Entertainment
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('The Evolution of Streaming Services',       'How we watch content has changed forever.','Netflix, launched as a DVD postal service in 1997, pioneered subscription streaming and transformed Hollywood. Today, competition from Disney+, HBO Max, Apple TV+, Amazon Prime, and dozens of regional platforms has fragmented audiences and driven massive investment in original content production.',                       200, 78, 6, 'ACT', 'https://picsum.photos/seed/streaming/800/600',6, NULL, NOW() - INTERVAL '88 days', 'system'),
('Top 10 Podcasts to Listen to in 2024',      'Audio content for every interest.',       'Podcasting has matured into a rich medium with content spanning true crime, business, science, comedy, and culture. Standouts include Lex Fridman Podcast for technology and philosophy, My Favourite Murder for true crime comedy, Huberman Lab for science-backed health insights, and Conan O''Brien Needs a Friend for pure laughs.', 175, 65, 4, 'ACT', 'https://picsum.photos/seed/podcast/800/600',  6, NULL, NOW() - INTERVAL '85 days', 'system'),
('Gaming in 2024: Trends to Watch',           'The future of interactive entertainment.','Cloud gaming, generative AI in game development, and the maturation of VR headsets are reshaping gaming. Xbox Game Pass and PlayStation Now have shifted monetisation from single purchases to subscription access. Indie games continue to win critical acclaim and outsell major studio titles on digital storefronts.',            185, 70, 5, 'ACT', 'https://picsum.photos/seed/gaming/800/600',   6, NULL, NOW() - INTERVAL '82 days', 'system'),
('The Return of Vinyl Records',               'Why analogue is thriving in a digital age.','Vinyl record sales have grown for 18 consecutive years. Audiophiles cite warmer sound and the tactile ritual of playing records as primary reasons. Limited editions, coloured pressings, and bundled download codes have made vinyl a collectible format that streaming cannot replicate.',                                        140, 52, 3, 'ACT', 'https://picsum.photos/seed/vinyl/800/600',    6, NULL, NOW() - INTERVAL '79 days', 'system'),
('Best Sci-Fi Books of the Decade',           'Essential reads for science fiction fans.','Ann Leckie''s Ancillary Justice redefined space opera. Andy Weir''s The Martian brought rigorous science back to the genre. NK Jemisin''s Broken Earth trilogy won three consecutive Hugo Awards. China Miéville''s Embassytown explores linguistic philosophy through alien contact. These works demonstrate the genre''s extraordinary range.', 130, 48, 2, 'ACT', 'https://picsum.photos/seed/scifi/800/600',    6, NULL, NOW() - INTERVAL '76 days', 'system'),
('Film Score Appreciation Guide',             'The music that makes movies emotional.',  'A great film score does not merely accompany the action — it shapes how audiences feel. John Williams, Ennio Morricone, Bernard Herrmann, and Hans Zimmer created musical vocabularies that define their respective eras. Leitmotifs — recurring themes associated with characters — are the most powerful compositional tool in a film composer''s arsenal.', 110, 40, 2, 'ACT', 'https://picsum.photos/seed/score/800/600',    6, NULL, NOW() - INTERVAL '73 days', 'system'),
('The Art of Stand-Up Comedy',                'What makes a joke actually work.',        'Stand-up comedy is a craft built on structure, timing, and truth. The most effective jokes subvert expectations — they establish a premise, build tension, then deliver a punchline that surprises but feels inevitable in retrospect. The best comedians mine personal experience and cultural observation for material that resonates universally.', 155, 58, 4, 'ACT', 'https://picsum.photos/seed/comedy/800/600',   6, NULL, NOW() - INTERVAL '70 days', 'system'),
('Modern Art: Why It Matters',                'Understanding contemporary art movements.','Contemporary art challenges viewers to question assumptions about beauty, meaning, and value. Movements like street art, NFT art, installation art, and social practice art expand the definition of what art can be and who it is for. Visiting galleries and reading artist statements are the fastest routes to genuine appreciation.', 100, 36, 3, 'ACT', 'https://picsum.photos/seed/art/800/600',      6, NULL, NOW() - INTERVAL '67 days', 'system'),
('Photography as an Art Form',                'Beyond documentation and into expression.','Photography transcends documentation when the photographer brings intention to every compositional decision — focal length, aperture, shutter speed, moment of capture, and post-processing. Henri Cartier-Bresson''s concept of the decisive moment captures the philosophy perfectly: anticipate and capture the split second when composition, light, and meaning align.', 125, 46, 2, 'ACT', 'https://picsum.photos/seed/photoart/800/600', 6, NULL, NOW() - INTERVAL '64 days', 'system'),
('Theatre in the Digital Age',                'Live performance in a streaming world.',  'Theatre remains uniquely irreplaceable despite competition from digital entertainment. The liveness, collective experience, and immediacy of theatre creates an atmosphere no screen can replicate. Broadway and West End productions increasingly invest in immersive formats, theatrical podcasts, and live-streamed performances to reach new audiences.', 90,  33, 2, 'ACT', 'https://picsum.photos/seed/theatre/800/600',  6, NULL, NOW() - INTERVAL '61 days', 'system');

-- Category 7: Sports
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('The Psychology of Peak Athletic Performance','What separates champions from the rest.','Elite athletes do not win on physical talent alone. Visualisation, pre-performance routines, self-talk management, and the ability to enter a flow state consistently separate world-class competitors from equally talented peers. Sports psychologists now work alongside strength coaches and nutritionists in every professional team.',  220, 88, 5, 'ACT', 'https://picsum.photos/seed/perf/800/600',     7, NULL, NOW() - INTERVAL '87 days', 'system'),
('Football Tactics Explained',                'Understanding the modern game.',          'Modern football has evolved from rigid formations to fluid positional play. The 4-3-3 and 4-2-3-1 remain popular, but positional play (Juego de Posición) championed by Pep Guardiola''s teams emphasises occupying and exploiting spaces rather than tracking opponents. High pressing and gegenpressing have reshaped how teams defend.',  195, 75, 6, 'ACT', 'https://picsum.photos/seed/football/800/600',  7, NULL, NOW() - INTERVAL '84 days', 'system'),
('Marathon Training: From Zero to Finish Line','Your 18-week marathon guide.',           'Training for a first marathon requires building aerobic base, practising long runs on race-day conditions, tapering correctly in the final three weeks, and dialling in nutrition and hydration strategy. The most common mistake is training too fast on easy days, accumulating fatigue before peak week.',                            170, 64, 4, 'ACT', 'https://picsum.photos/seed/marathon/800/600',  7, NULL, NOW() - INTERVAL '81 days', 'system'),
('Swimming Technique Breakdown',              'Go faster with better form, not more effort.','Efficient swimming is about minimising drag and maximising propulsion. The freestyle catch — pressing the arm forward and down before the pull — is the most impactful technique element to improve. A Total Immersion or swimming coach analysis session reveals inefficiencies that months of unsupervised practice will never fix.',  130, 48, 2, 'ACT', 'https://picsum.photos/seed/swim/800/600',     7, NULL, NOW() - INTERVAL '78 days', 'system'),
('The Business of Esports',                   'Gaming as a billion-dollar industry.',    'Esports revenues exceeded $1.8 billion in 2023, driven by sponsorships, media rights, merchandise, and ticket sales. Titles like League of Legends, Valorant, CS:GO, and Dota 2 fill arenas and attract audiences that rival traditional sports among the 18–35 demographic. Investor interest in esports franchises continues to grow.',  210, 82, 7, 'ACT', 'https://picsum.photos/seed/esports/800/600',  7, NULL, NOW() - INTERVAL '75 days', 'system'),
('Cycling for Commuters',                     'Make cycling your daily transport.',      'Urban cycling reduces commute costs, improves cardiovascular fitness, and avoids traffic congestion. Key investments are a reliable lock, front and rear lights, a quality helmet, and puncture-resistant tyres. Plan routes using cycling infrastructure apps and practise confident lane positioning to ride safely in traffic.',         145, 54, 3, 'ACT', 'https://picsum.photos/seed/cycling/800/600',  7, NULL, NOW() - INTERVAL '72 days', 'system'),
('Understanding Cricket for Beginners',       'A guide to the world''s second-most-watched sport.','Cricket is played between two teams of 11. The batting team scores runs while the fielding team attempts dismissals. Test cricket spans five days; T20 matches finish in three hours. Understanding the LBW rule, the swing of a Dukes ball, and the role of the pitch condition unlocks appreciation of the sport''s extraordinary depth.', 115, 42, 3, 'ACT', 'https://picsum.photos/seed/cricket/800/600',  7, NULL, NOW() - INTERVAL '69 days', 'system'),
('Nutrition for Endurance Athletes',          'Fuel long efforts properly.',             'Endurance athletes have dramatically elevated carbohydrate requirements. Glycogen depletion — hitting the wall — is the primary limiter in events lasting over 90 minutes. Practise in-race nutrition during training, target 60–90g of carbohydrate per hour from mixed sugar sources, and prioritise rehydration and protein recovery post-event.', 160, 60, 4, 'ACT', 'https://picsum.photos/seed/endurance/800/600', 7, NULL, NOW() - INTERVAL '66 days', 'system'),
('Rock Climbing: Getting Started',            'Your introduction to vertical movement.',  'Rock climbing develops total-body strength, problem-solving, and mental fortitude. Bouldering — climbing short, powerful routes without a rope — is the most accessible entry point, available at indoor gyms worldwide. Footwork and body positioning are more important than raw upper-body strength for new climbers.',                 135, 50, 2, 'ACT', 'https://picsum.photos/seed/climbing/800/600', 7, NULL, NOW() - INTERVAL '63 days', 'system'),
('The Rise of Pickleball',                    'America''s fastest growing sport.',       'Pickleball, a paddle sport combining elements of tennis, badminton, and table tennis, has grown from a backyard game into a professional sport with dedicated arenas and television broadcast deals. It is particularly popular with older adults due to its lower impact compared to tennis, but its competitive ceiling is surprisingly high.', 180, 68, 5, 'ACT', 'https://picsum.photos/seed/pickleball/800/600',7, NULL, NOW() - INTERVAL '60 days', 'system');

-- Category 8: Science
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('James Webb Telescope: First Year Results', 'What we have learned about the early universe.','The James Webb Space Telescope has already revolutionised astronomy in its first year. Images reaching back to 300 million years after the Big Bang revealed galaxies larger and more structured than cosmological models predicted. Webb is also detecting atmospheric compositions of exoplanets with unprecedented precision.',            240, 95, 4, 'ACT', 'https://picsum.photos/seed/webb/800/600',     8, NULL, NOW() - INTERVAL '86 days', 'system'),
('CRISPR and the Gene Editing Revolution',   'Rewriting the code of life.',             'CRISPR-Cas9 allows scientists to precisely cut and edit DNA sequences. Applications range from correcting genetic diseases like sickle cell anaemia to developing disease-resistant crops and engineering mosquitoes that cannot transmit malaria. The first CRISPR therapy for sickle cell disease received FDA approval in December 2023.',  200, 78, 5, 'ACT', 'https://picsum.photos/seed/crispr/800/600',   8, NULL, NOW() - INTERVAL '83 days', 'system'),
('The Gut-Brain Connection',                 'Your second brain and what it means.',    'The enteric nervous system — 500 million neurons lining the gastrointestinal tract — communicates bidirectionally with the brain via the vagus nerve. Gut microbiome composition influences neurotransmitter production, immune function, and mood. Research is exploring links between gut dysbiosis and depression, anxiety, and Parkinson''s disease.',  175, 66, 3, 'ACT', 'https://picsum.photos/seed/gut/800/600',      8, NULL, NOW() - INTERVAL '80 days', 'system'),
('Dark Matter: What We Know',                'The invisible substance shaping the cosmos.','Dark matter comprises approximately 27% of the universe yet emits no light or radiation, making it undetectable by conventional means. Its existence is inferred from gravitational effects — the rotation curves of galaxies, gravitational lensing, and large-scale cosmic structure formation all require dark matter to be explained.',   155, 58, 4, 'ACT', 'https://picsum.photos/seed/dark/800/600',     8, NULL, NOW() - INTERVAL '77 days', 'system'),
('Climate Science Fundamentals',             'Understanding the evidence behind climate change.','The scientific consensus on anthropogenic climate change rests on multiple independent lines of evidence: rising atmospheric CO₂, ocean warming and acidification, glacial retreat, rising sea levels, and shifts in species ranges. Climate models project warming of 1.5–4.5°C above pre-industrial levels by 2100 depending on emissions trajectories.', 190, 72, 8, 'ACT', 'https://picsum.photos/seed/climate/800/600',  8, NULL, NOW() - INTERVAL '74 days', 'system'),
('Nuclear Fusion: Closer Than Ever',         'The power of the stars, on Earth.',       'In December 2022, the National Ignition Facility achieved fusion ignition for the first time — producing more energy from a fusion reaction than the lasers delivered. Commercial fusion power remains 10–20 years away, but companies like Commonwealth Fusion and TAE Technologies are attracting billions in private investment.',             165, 62, 3, 'ACT', 'https://picsum.photos/seed/fusion/800/600',   8, NULL, NOW() - INTERVAL '71 days', 'system'),
('Epigenetics: Beyond the Genetic Code',     'How environment shapes gene expression.', 'Epigenetics studies heritable changes in gene expression that do not involve alterations to the DNA sequence itself. Environmental factors — diet, stress, trauma, and toxin exposure — can switch genes on or off and, in some cases, pass these changes to subsequent generations. The field challenges the deterministic view of genetics.',  140, 52, 2, 'ACT', 'https://picsum.photos/seed/epigen/800/600',   8, NULL, NOW() - INTERVAL '68 days', 'system'),
('The Mathematics of Artificial Intelligence','Why linear algebra and calculus power AI.','Modern AI is applied mathematics. Neural networks are chains of matrix multiplications. Backpropagation uses calculus chain rule to optimise billions of parameters. Probability theory underpins uncertainty quantification. Understanding these mathematical foundations demystifies the black box and enables more effective model development.',  130, 48, 3, 'ACT', 'https://picsum.photos/seed/mathml/800/600',   8, NULL, NOW() - INTERVAL '65 days', 'system'),
('Antibiotic Resistance Crisis',             'One of medicine''s greatest threats.',    'The World Health Organisation classifies antimicrobial resistance as one of the greatest threats to global health. Overuse of antibiotics in human medicine and agriculture accelerates the evolution of resistant strains. Phage therapy, antimicrobial peptides, and CRISPR-based antimicrobials are promising alternatives under development.',  150, 56, 4, 'ACT', 'https://picsum.photos/seed/antibio/800/600',  8, NULL, NOW() - INTERVAL '62 days', 'system'),
('How Memory Works in the Human Brain',      'The neuroscience of remembering.',        'Memory formation involves three stages: encoding (converting experience into neural signals), storage (consolidating information during sleep), and retrieval (reconstructing stored patterns). Long-term potentiation — the strengthening of synaptic connections through repeated activation — is the cellular mechanism underlying learning.',  120, 45, 2, 'ACT', 'https://picsum.photos/seed/memory/800/600',   8, NULL, NOW() - INTERVAL '59 days', 'system');

-- Category 9: Education
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('The Future of Online Learning',             'How EdTech is reshaping education.',      'Platforms like Coursera, edX, Khan Academy, and Duolingo have democratised access to world-class education. Micro-credentials and nanodegrees allow professionals to upskill faster than traditional degree programmes permit. AI tutors that adapt to individual learning pace and style represent the next frontier.',                        185, 70, 4, 'ACT', 'https://picsum.photos/seed/edtech/800/600',   9, NULL, NOW() - INTERVAL '88 days', 'system'),
('How to Learn Anything Faster',             'Evidence-based learning techniques.',     'Spaced repetition, interleaving, retrieval practice, and elaborative interrogation are among the most research-supported learning techniques. Passive re-reading and highlighting are among the least effective despite their popularity. The Feynman technique — explaining concepts simply as if teaching a child — reveals gaps in understanding rapidly.', 200, 78, 5, 'ACT', 'https://picsum.photos/seed/learn/800/600',    9, NULL, NOW() - INTERVAL '85 days', 'system'),
('Critical Thinking in the Age of Misinformation','How to evaluate what you read online.','Critical thinking requires identifying logical fallacies, evaluating source credibility, distinguishing between correlation and causation, seeking disconfirming evidence, and recognising cognitive biases like confirmation bias and availability heuristic. Lateral reading — checking sources before reading deeply — is the method used by professional fact-checkers.', 175, 66, 5, 'ACT', 'https://picsum.photos/seed/critical/800/600', 9, NULL, NOW() - INTERVAL '82 days', 'system'),
('Learning a Second Language: What Works',   'The science-backed path to fluency.',     'Comprehensible input — material slightly above your current level — is the most efficient language acquisition mechanism. Apps like Anki for vocabulary flashcards, language exchange platforms like iTalki for conversation practice, and immersion through media in the target language accelerate progress beyond grammar-focused study alone.',  160, 60, 3, 'ACT', 'https://picsum.photos/seed/language/800/600', 9, NULL, NOW() - INTERVAL '79 days', 'system'),
('The Montessori Method Explained',          'A different approach to childhood education.','Maria Montessori developed her educational philosophy from observational research with children in Rome in 1907. The method emphasises child-led learning, mixed-age classrooms, uninterrupted work periods, and specially designed manipulative materials. Research shows Montessori-educated children demonstrate stronger executive function and intrinsic motivation.', 135, 50, 2, 'ACT', 'https://picsum.photos/seed/montessori/800/600',9, NULL, NOW() - INTERVAL '76 days', 'system'),
('Philosophy for Beginners',                 'Great questions and how to think about them.','Philosophy teaches you how to think rigorously about fundamental questions: what exists, how we can know it, how we should live, and what is just. Engaging with Plato, Aristotle, Descartes, Kant, Nietzsche, and contemporary philosophers like Peter Singer builds the mental toolkit to navigate complexity and resist manipulation.',  120, 45, 2, 'ACT', 'https://picsum.photos/seed/philosophy/800/600',9, NULL, NOW() - INTERVAL '73 days', 'system'),
('History of Mathematics',                   'The human story behind the numbers.',     'Mathematics was developed independently across civilisations — Mesopotamian accountants, Egyptian surveyors, Greek geometers, Indian algebraists, and Arab scholars each contributed foundational elements. Newton and Leibniz independently invented calculus. Ramanujan, largely self-taught, produced results that still fuel research a century later.',  115, 42, 2, 'ACT', 'https://picsum.photos/seed/mathhistory/800/600',9, NULL, NOW() - INTERVAL '70 days', 'system'),
('Teaching Kids to Code',                    'Coding as the new literacy.',             'Coding teaches logical thinking, decomposition, pattern recognition, and algorithmic design — skills that transfer far beyond software development. Scratch (MIT), Code.org, and Raspberry Pi Foundation resources provide age-appropriate entry points. Pair programming, game-based learning, and physical computing with Arduino or micro:bit make the subject tangible.',  145, 54, 3, 'ACT', 'https://picsum.photos/seed/kidscode/800/600', 9, NULL, NOW() - INTERVAL '67 days', 'system'),
('The History of Writing',                   'How humanity learned to record itself.',  'Writing was invented independently at least three times: in Mesopotamia around 3400 BCE (cuneiform), in China around 1200 BCE (oracle bone script), and in Mesoamerica around 900 BCE. Each system evolved from pictographic origins toward phonetic representation. The Phoenician alphabet, ancestor of most modern scripts, appeared around 1050 BCE.',  105, 38, 1, 'ACT', 'https://picsum.photos/seed/writing/800/600',  9, NULL, NOW() - INTERVAL '64 days', 'system'),
('Growth Mindset vs Fixed Mindset',          'Carol Dweck''s transformative framework.','Psychologist Carol Dweck''s research demonstrates that people with a growth mindset — believing abilities develop through effort — outperform those with a fixed mindset across domains including academic performance, athletic achievement, and business outcomes. Praising effort rather than innate talent cultivates a growth mindset in children and adults alike.', 190, 72, 4, 'ACT', 'https://picsum.photos/seed/mindset/800/600',  9, NULL, NOW() - INTERVAL '61 days', 'system');

-- Category 10: Lifestyle
INSERT INTO posts (title, description, body, total_view, likes, dislikes, status, image, category_id, user_id, created_at, created_by) VALUES
('Minimalism: Living with Less',             'Why less can be so much more.',           'Minimalism is not about deprivation — it is about intentionality. By eliminating possessions, commitments, and digital clutter that do not align with your values, you create space for what matters. The KonMari method, Project 333 (33 items of clothing for 3 months), and a regular possessions audit are practical starting points.',  170, 64, 4, 'ACT', 'https://picsum.photos/seed/minimal/800/600',  10, NULL, NOW() - INTERVAL '89 days', 'system'),
('Personal Finance in Your 20s',             'Build wealth early through smart habits.','Your 20s are the most powerful decade for wealth building due to compound interest. Prioritise: eliminating high-interest debt, building a 3–6 month emergency fund, maximising employer pension matching, then investing in low-cost index funds. Time in market consistently beats timing the market over 20-year horizons.',             185, 70, 5, 'ACT', 'https://picsum.photos/seed/pf20s/800/600',    10, NULL, NOW() - INTERVAL '86 days', 'system'),
('Creating a Morning Routine That Works',    'Own your mornings, own your day.',        'Effective morning routines are personal — what works is what you will sustain. Common elements of high performers include: physical movement, journaling or meditation, reviewing priorities for the day, and protecting the first 90 minutes from email and social media. Start with one change and build incrementally.',                   155, 58, 3, 'ACT', 'https://picsum.photos/seed/morning/800/600',  10, NULL, NOW() - INTERVAL '83 days', 'system'),
('The Art of Deep Work',                     'Produce more, distract less.',            'Cal Newport''s concept of deep work — cognitively demanding professional activity performed without distraction — produces output that is rare and valuable. Schedule 2–4 hour blocks of uninterrupted focus, eliminate notifications, batch shallow tasks like email into designated time slots, and quit social media as a default behaviour.',  175, 66, 4, 'ACT', 'https://picsum.photos/seed/deepwork/800/600', 10, NULL, NOW() - INTERVAL '80 days', 'system'),
('Interior Design on a Budget',              'Make your home beautiful without overspending.','Great interior design is about proportion, colour, light, and texture — not budget. Secondhand furniture platforms, DIY projects, strategic paint colour choices, quality lighting fixtures, and thoughtful plant placement can transform a space for a fraction of retail cost. Start with decluttering before any purchases.',              135, 50, 2, 'ACT', 'https://picsum.photos/seed/interior/800/600', 10, NULL, NOW() - INTERVAL '77 days', 'system'),
('Sustainable Fashion Guide',                'Dress well, waste less.',                 'The fashion industry is responsible for 10% of global CO₂ emissions and 20% of industrial water pollution. Sustainable alternatives include buying secondhand, choosing natural fibres, investing in quality over quantity, participating in clothing swaps, and supporting brands that publish transparent supply chain data.',                    150, 56, 4, 'ACT', 'https://picsum.photos/seed/fashion/800/600',  10, NULL, NOW() - INTERVAL '74 days', 'system'),
('The Case for Journaling',                  'Writing to understand yourself.',         'Journaling provides a low-cost, high-return tool for emotional processing, goal clarification, and cognitive offloading. Research supports its efficacy in reducing anxiety, processing trauma, improving working memory, and enhancing self-awareness. Even five minutes of unstructured free-writing daily produces measurable benefits.',         125, 46, 2, 'ACT', 'https://picsum.photos/seed/journal/800/600',  10, NULL, NOW() - INTERVAL '71 days', 'system'),
('Building Better Habits',                   'The science of behaviour change.',        'James Clear''s Atomic Habits distills habit research into four laws: make it obvious, make it attractive, make it easy, and make it satisfying. Habit stacking — linking a new behaviour to an established one — leverages existing neural pathways. Tracking systems and environment design are more reliable than motivation and willpower.',  200, 78, 5, 'ACT', 'https://picsum.photos/seed/habits/800/600',   10, NULL, NOW() - INTERVAL '68 days', 'system'),
('The Joy of Slow Travel',                   'Why going slower means experiencing more.','Slow travel — staying in a destination for weeks rather than days — allows genuine connection with local culture, language, and people. Renting an apartment, shopping at local markets, attending neighbourhood events, and learning basic phrases in the local language transforms tourist into temporary resident.',                           145, 54, 3, 'ACT', 'https://picsum.photos/seed/slow/800/600',    10, NULL, NOW() - INTERVAL '65 days', 'system'),
('Digital Detox: Reclaiming Your Attention', 'Break free from your screen addiction.', 'The average person checks their phone 96 times per day. Social media platforms are designed by teams of psychologists to maximise engagement through variable reward schedules — the same mechanism that makes slot machines addictive. A structured digital detox, app time limits, grayscale display mode, and designated phone-free hours restore intentional attention control.', 165, 62, 6, 'ACT', 'https://picsum.photos/seed/detox/800/600',   10, NULL, NOW() - INTERVAL '62 days', 'system');

-- ============================================================
-- post_tags (sample tags per post)
-- ============================================================
INSERT INTO post_tags (post_id, tag)
SELECT p.id, t.tag
FROM posts p
CROSS JOIN LATERAL (
    VALUES
        (CASE WHEN p.category_id = 1  THEN 'technology'   WHEN p.category_id = 2  THEN 'travel'       WHEN p.category_id = 3  THEN 'food'
              WHEN p.category_id = 4  THEN 'health'       WHEN p.category_id = 5  THEN 'business'     WHEN p.category_id = 6  THEN 'entertainment'
              WHEN p.category_id = 7  THEN 'sports'       WHEN p.category_id = 8  THEN 'science'      WHEN p.category_id = 9  THEN 'education'
              ELSE 'lifestyle' END),
        (CASE WHEN p.category_id IN (1,8)  THEN 'trending'  WHEN p.category_id IN (2,10) THEN 'popular'
              WHEN p.category_id IN (3,4)  THEN 'wellness'  WHEN p.category_id IN (5,9)  THEN 'knowledge'
              ELSE 'featured' END),
        ('english')
) AS t(tag)
WHERE p.status = 'ACT';
